sonar.projectKey=health_platform_clinic-platform
sonar.projectName=Clinic Platform
sonar.projectDescription=Clinic Platform

# Scan Performace
sonar.javascript.node.maxspace=24576
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,*.png
