/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardStaffIndexRouteImport } from './routes/_dashboard/staff/index'
import { Route as DashboardShiftsIndexRouteImport } from './routes/_dashboard/shifts/index'
import { Route as DashboardShiftTemplatesIndexRouteImport } from './routes/_dashboard/shift-templates/index'
import { Route as DashboardPatientsIndexRouteImport } from './routes/_dashboard/patients/index'
import { Route as DashboardDoctorsIndexRouteImport } from './routes/_dashboard/doctors/index'
import { Route as DashboardDepartmentsIndexRouteImport } from './routes/_dashboard/departments/index'
import { Route as DashboardBookingsIndexRouteImport } from './routes/_dashboard/bookings/index'
import { Route as DashboardDoctorsDoctorIdRouteImport } from './routes/_dashboard/doctors/$doctorId'
import { Route as DashboardBookingsBookingIdRouteImport } from './routes/_dashboard/bookings/$bookingId'
import { Route as DashboardDepartmentsDepartmentIdIndexRouteImport } from './routes/_dashboard/departments/$departmentId/index'
import { Route as DashboardDoctorsDoctorIdSlotsRouteImport } from './routes/_dashboard/doctors/$doctorId/slots'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardStaffIndexRoute = DashboardStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftsIndexRoute = DashboardShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftTemplatesIndexRoute =
  DashboardShiftTemplatesIndexRouteImport.update({
    id: '/shift-templates/',
    path: '/shift-templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPatientsIndexRoute = DashboardPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsIndexRoute = DashboardDoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsIndexRoute =
  DashboardDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsIndexRoute = DashboardBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoctorsDoctorIdRoute =
  DashboardDoctorsDoctorIdRouteImport.update({
    id: '/doctors/$doctorId',
    path: '/doctors/$doctorId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBookingsBookingIdRoute =
  DashboardBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDepartmentsDepartmentIdIndexRoute =
  DashboardDepartmentsDepartmentIdIndexRouteImport.update({
    id: '/departments/$departmentId/',
    path: '/departments/$departmentId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDoctorsDoctorIdSlotsRoute =
  DashboardDoctorsDoctorIdSlotsRouteImport.update({
    id: '/slots',
    path: '/slots',
    getParentRoute: () => DashboardDoctorsDoctorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/doctors/$doctorId': typeof DashboardDoctorsDoctorIdRouteWithChildren
  '/bookings/': typeof DashboardBookingsIndexRoute
  '/departments/': typeof DashboardDepartmentsIndexRoute
  '/doctors/': typeof DashboardDoctorsIndexRoute
  '/patients/': typeof DashboardPatientsIndexRoute
  '/shift-templates/': typeof DashboardShiftTemplatesIndexRoute
  '/shifts/': typeof DashboardShiftsIndexRoute
  '/staff/': typeof DashboardStaffIndexRoute
  '/doctors/$doctorId/slots': typeof DashboardDoctorsDoctorIdSlotsRoute
  '/departments/$departmentId/': typeof DashboardDepartmentsDepartmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/doctors/$doctorId': typeof DashboardDoctorsDoctorIdRouteWithChildren
  '/bookings': typeof DashboardBookingsIndexRoute
  '/departments': typeof DashboardDepartmentsIndexRoute
  '/doctors': typeof DashboardDoctorsIndexRoute
  '/patients': typeof DashboardPatientsIndexRoute
  '/shift-templates': typeof DashboardShiftTemplatesIndexRoute
  '/shifts': typeof DashboardShiftsIndexRoute
  '/staff': typeof DashboardStaffIndexRoute
  '/doctors/$doctorId/slots': typeof DashboardDoctorsDoctorIdSlotsRoute
  '/departments/$departmentId': typeof DashboardDepartmentsDepartmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/bookings/$bookingId': typeof DashboardBookingsBookingIdRoute
  '/_dashboard/doctors/$doctorId': typeof DashboardDoctorsDoctorIdRouteWithChildren
  '/_dashboard/bookings/': typeof DashboardBookingsIndexRoute
  '/_dashboard/departments/': typeof DashboardDepartmentsIndexRoute
  '/_dashboard/doctors/': typeof DashboardDoctorsIndexRoute
  '/_dashboard/patients/': typeof DashboardPatientsIndexRoute
  '/_dashboard/shift-templates/': typeof DashboardShiftTemplatesIndexRoute
  '/_dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/_dashboard/staff/': typeof DashboardStaffIndexRoute
  '/_dashboard/doctors/$doctorId/slots': typeof DashboardDoctorsDoctorIdSlotsRoute
  '/_dashboard/departments/$departmentId/': typeof DashboardDepartmentsDepartmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookings/$bookingId'
    | '/doctors/$doctorId'
    | '/bookings/'
    | '/departments/'
    | '/doctors/'
    | '/patients/'
    | '/shift-templates/'
    | '/shifts/'
    | '/staff/'
    | '/doctors/$doctorId/slots'
    | '/departments/$departmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bookings/$bookingId'
    | '/doctors/$doctorId'
    | '/bookings'
    | '/departments'
    | '/doctors'
    | '/patients'
    | '/shift-templates'
    | '/shifts'
    | '/staff'
    | '/doctors/$doctorId/slots'
    | '/departments/$departmentId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/'
    | '/_dashboard/bookings/$bookingId'
    | '/_dashboard/doctors/$doctorId'
    | '/_dashboard/bookings/'
    | '/_dashboard/departments/'
    | '/_dashboard/doctors/'
    | '/_dashboard/patients/'
    | '/_dashboard/shift-templates/'
    | '/_dashboard/shifts/'
    | '/_dashboard/staff/'
    | '/_dashboard/doctors/$doctorId/slots'
    | '/_dashboard/departments/$departmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/staff/': {
      id: '/_dashboard/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof DashboardStaffIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shifts/': {
      id: '/_dashboard/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof DashboardShiftsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/shift-templates/': {
      id: '/_dashboard/shift-templates/'
      path: '/shift-templates'
      fullPath: '/shift-templates/'
      preLoaderRoute: typeof DashboardShiftTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/patients/': {
      id: '/_dashboard/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof DashboardPatientsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/doctors/': {
      id: '/_dashboard/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DashboardDoctorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/departments/': {
      id: '/_dashboard/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DashboardDepartmentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/': {
      id: '/_dashboard/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof DashboardBookingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/doctors/$doctorId': {
      id: '/_dashboard/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DashboardDoctorsDoctorIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/bookings/$bookingId': {
      id: '/_dashboard/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof DashboardBookingsBookingIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/departments/$departmentId/': {
      id: '/_dashboard/departments/$departmentId/'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId/'
      preLoaderRoute: typeof DashboardDepartmentsDepartmentIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/doctors/$doctorId/slots': {
      id: '/_dashboard/doctors/$doctorId/slots'
      path: '/slots'
      fullPath: '/doctors/$doctorId/slots'
      preLoaderRoute: typeof DashboardDoctorsDoctorIdSlotsRouteImport
      parentRoute: typeof DashboardDoctorsDoctorIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardDoctorsDoctorIdRouteChildren {
  DashboardDoctorsDoctorIdSlotsRoute: typeof DashboardDoctorsDoctorIdSlotsRoute
}

const DashboardDoctorsDoctorIdRouteChildren: DashboardDoctorsDoctorIdRouteChildren =
  {
    DashboardDoctorsDoctorIdSlotsRoute: DashboardDoctorsDoctorIdSlotsRoute,
  }

const DashboardDoctorsDoctorIdRouteWithChildren =
  DashboardDoctorsDoctorIdRoute._addFileChildren(
    DashboardDoctorsDoctorIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBookingsBookingIdRoute: typeof DashboardBookingsBookingIdRoute
  DashboardDoctorsDoctorIdRoute: typeof DashboardDoctorsDoctorIdRouteWithChildren
  DashboardBookingsIndexRoute: typeof DashboardBookingsIndexRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
  DashboardDoctorsIndexRoute: typeof DashboardDoctorsIndexRoute
  DashboardPatientsIndexRoute: typeof DashboardPatientsIndexRoute
  DashboardShiftTemplatesIndexRoute: typeof DashboardShiftTemplatesIndexRoute
  DashboardShiftsIndexRoute: typeof DashboardShiftsIndexRoute
  DashboardStaffIndexRoute: typeof DashboardStaffIndexRoute
  DashboardDepartmentsDepartmentIdIndexRoute: typeof DashboardDepartmentsDepartmentIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBookingsBookingIdRoute: DashboardBookingsBookingIdRoute,
  DashboardDoctorsDoctorIdRoute: DashboardDoctorsDoctorIdRouteWithChildren,
  DashboardBookingsIndexRoute: DashboardBookingsIndexRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
  DashboardDoctorsIndexRoute: DashboardDoctorsIndexRoute,
  DashboardPatientsIndexRoute: DashboardPatientsIndexRoute,
  DashboardShiftTemplatesIndexRoute: DashboardShiftTemplatesIndexRoute,
  DashboardShiftsIndexRoute: DashboardShiftsIndexRoute,
  DashboardStaffIndexRoute: DashboardStaffIndexRoute,
  DashboardDepartmentsDepartmentIdIndexRoute:
    DashboardDepartmentsDepartmentIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
